### ISSUE TITLE
Issue with property named `get` inside classes

### ISSUE THREAD

**Issue by yspreen** [awslabs/llrt#296] opened 2024-03-25 02:25 UTC
Express and Drizzle both have classes with property methods called `get`. It seems to be fine if defined like
```
get(/* args */) {
  /* method */
}
```

but this line in drizzle: https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-orm/src/sqlite-core/query-builders/delete.ts#L251

	get: ReturnType<this['prepare']>['get'] = (placeholderValues) => {
		return this._prepare().get(placeholderValues);
	};

causes issues in LLRT when compiled with TS and bundled with rollup.js:

```
invalid property name
```

because the compiled result is

```
get = (e) => this._prepare().get(e);
```

**Comment by richarddavison** [comment] 2024-03-25 10:58
Hi @yspreen, thanks for the report. Do you have a minimum reproducible js file?

**Comment by yspreen** [comment] 2024-03-26 02:24
```
~/Downloads/llrt ./test.js
SyntaxError: invalid property name
    at ./test.js:2:6
```

```js
class TestClass {
  get = () => console.log("get");
}

new TestClass().get();

```

**Comment by yspreen** [comment] 2024-03-26 02:24
as mentioned above, it only breaks if you set it to an anonymous method. not if defining get() {}

**Comment by richarddavison** [comment] 2024-04-02 09:11
I've located the issue and submitted a patch to downstream QuickJS engine. The catch is that we're not up to date on the latest version. However, we can (and already do) apply patches independently of the engine:
https://github.com/bellard/quickjs/pull/258

**Comment by nabetti1720** [comment] 2024-08-30 12:39
Thanks for the information. I had completely overlooked the quickjs-ng initiative.
As for the newly cut out issue, I will close it. :)

**Comment by richarddd** [comment] 2024-10-21 14:10
Should work in latest release due to updated QJS version. Can you check again @yspreen ?

**Comment by richarddavison** [comment] 2024-11-28 07:01
This is now resolved!

**Closed by richarddavison** 2024-11-28 07:01 UTC
Labels: bug
